// <auto-generated />
namespace TodoApp.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_task_add_start : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_task_add_start));
        
        string IMigrationMetadata.Id
        {
            get { return "202102141617480_update_task_add_start"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
